# Theme App Extension configuration
api_version = "2024-10"

[[extensions]]
uid = "96869fe4-d622-98ea-0cf5-2430da9abe9a465f8f5c"
type = "theme"
name = "Showcase3D Viewer"
handle = "showcase3d-viewer"

  [[extensions.assets]]
  filepath = "assets/viewer.js"

  [[extensions.assets]]
  filepath = "assets/viewer.css"

