/**
 * Emits `src/generated/route-manifest.ts` — the list of every URL this site
 * serves, with its title, description and markdown twin.
 *
 * Three consumers, one list, so they cannot disagree about what exists:
 *
 *   - `middleware.ts` (via `src/server/negotiation.ts`) resolves an incoming
 *     path to its markdown file, and answers a markdown 404 for anything not
 *     on the list.
 *   - `src/lib/page-meta.ts` sets each page's <title>, description and
 *     canonical URL.
 *   - `sitemap.xml` is generated from it.
 *
 * Unlike the other generated artefacts this one is committed: the app imports
 * it, so a fresh clone has to typecheck and `pnpm dev` has to run before
 * anything has been built.
 */

export type ManifestRoute = {
  path: string
  title: string
  description: string
  /** Path of the markdown twin served for `Accept: text/markdown`, if any. */
  markdown: string | null
  kind: "home" | "page" | "guide" | "component" | "index"
  priority: number
}

export function renderRouteManifest(routes: ManifestRoute[]): string {
  const body = routes
    .map(
      (route) =>
        "  " +
        JSON.stringify({
          path: route.path,
          title: route.title,
          description: route.description,
          markdown: route.markdown,
          kind: route.kind,
          priority: route.priority,
        })
    )
    .join(",\n")

  return `// AUTO-GENERATED by scripts/generate-llms.ts — do not edit by hand.
// Regenerate with \`pnpm gen:registry\`.
//
// Every URL this site serves, with the markdown twin content negotiation
// rewrites to. Committed rather than gitignored because the app imports it.

export type ManifestRoute = {
  path: string
  title: string
  description: string
  /** Path of the markdown twin served for \`Accept: text/markdown\`, if any. */
  markdown: string | null
  kind: "home" | "page" | "guide" | "component" | "index"
  /** Sitemap priority. */
  priority: number
}

export const ROUTE_MANIFEST: ManifestRoute[] = [
${body},
]

/** Path → route, for O(1) lookup in the edge middleware. */
export const ROUTE_BY_PATH: Record<string, ManifestRoute> = Object.fromEntries(
  ROUTE_MANIFEST.map((route) => [route.path, route])
)
`
}

export function renderSitemap(
  routes: ManifestRoute[],
  siteUrl: string,
  lastmod: string,
  extraUrls: Array<{ loc: string; priority: number }> = []
): string {
  const entries = [
    ...routes.map((route) => ({
      loc: `${siteUrl}${route.path === "/" ? "/" : route.path}`,
      priority: route.priority,
    })),
    ...extraUrls,
  ]

  const body = entries
    .map(
      (entry) =>
        `  <url>\n` +
        `    <loc>${entry.loc}</loc>\n` +
        `    <lastmod>${lastmod}</lastmod>\n` +
        `    <priority>${entry.priority.toFixed(2)}</priority>\n` +
        `  </url>`
    )
    .join("\n")

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-llms.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`
}
