/**
 * guides-registry.ts
 *
 * Canonical source for the docs guide pages emitted into
 * `public/llms/_guides/{slug}.md` by `generate-llms.ts`. Mirrors the role of
 * `src/components/docs/registry.tsx` for components: a single source of
 * structured data the generator imports.
 *
 * Why content lives here, not in the route .tsx files:
 *   The route files render styled JSX with Tailwind classes, mapped arrays,
 *   interactive components (`ThemePlayground`), and Callouts. Parsing that
 *   JSX into AI-readable markdown is fragile — better to keep an authoritative
 *   markdown copy here, optimised for AI consumption, and accept the small
 *   cost of updating both when prose changes.
 *
 * Body strings may contain two placeholders that the generator substitutes:
 *   {{SITE_URL}}     — the deployed docs URL
 *   {{PACKAGE_NAME}} — the npm package name (provisional until published)
 *
 * Internal `[label](/docs/...)` links are rewritten to absolute URLs by the
 * generator's `absolutizeDocsLinks()` helper. External links and anchors
 * (`#section-id`) pass through unchanged.
 */

import type { NoteDef } from "../src/components/docs/registry"

export type GuideDoc = {
  slug: string
  name: string
  /** One-line description used in the llms.txt index. */
  description: string
  /** Full markdown body. May contain {{SITE_URL}} / {{PACKAGE_NAME}} placeholders. */
  body: string
  /** Optional callouts rendered above the body, mirrors ComponentDoc.notes. */
  notes?: NoteDef[]
}

// ---------------------------------------------------------------------------
// Body content
// ---------------------------------------------------------------------------

const introductionBody = [
  "Drop-in React components for displaying verified AI agent data from the ERC-8004 standard — built for developers who don't want to become Subgraph experts.",
  "",
  "## Why this exists",
  "",
  "ERC-8004 is spreading across chains faster than the tooling around it. Teams building on the standard end up writing the same plumbing over and over — subgraph queries, chain-prefixed identifiers, three different URI formats, revoked-feedback filtering — before they can render a single agent name on screen.",
  "",
  "This library is the layer in between. You pass an agent's on-chain ID, you get a component that works. The point is to make ERC-8004 feel like any other API a frontend developer already knows how to consume.",
  "",
  "## Why use this library?",
  "",
  "Displaying ERC-8004 agent data looks straightforward — fetch some fields, render them. In practice, the Subgraph has enough quirks that AI-generated components will silently get things wrong. Not because the AI is bad at React, but because the domain-specific rules aren't in any training data.",
  "",
  "- **Feedback value has no universal scale** — Different agents receive scores on different ranges. You can't treat it like a standard 1–5 star rating without knowing the context.",
  "- **Tags aren't pre-aggregated** — `tag1` and `tag2` on each feedback entry aren't counted anywhere. You have to fetch all feedback and compute frequencies client-side.",
  "- **The deployed schema drifts from the docs** — The schema reference used in this library was captured from an actual Subgraph introspection query — not the SDK docs or the GitHub README.",
  "- **agentURI needs three resolution paths** — The registration file URI can be IPFS, HTTPS, or a base64 data URI. Each requires different handling.",
  "- **Revoked feedback must be filtered** — `isRevoked: false` needs to be in every feedback query. A component that omits it will silently include retracted reviews.",
  "- **Pagination is offset-based, not cursor-based** — The Subgraph uses `first`/`skip`, not a cursor. Deep pagination gets expensive and has known limitations.",
  "- **Chain ID → Subgraph endpoint mapping** — Each chain has a different Subgraph deployment ID, and every request needs your API key injected into the URL.",
  "- **Validation Registry isn't on mainnet yet** — The smart contracts are only deployed on testnets (Sepolia confirmed). The subgraph schema supports validation entities across all deployments, so `VerificationBadge`, `ValidationScore`, and `ValidationList` will build and test end-to-end on Sepolia. On mainnet, validation queries return empty by design, not because something is broken. Components must render an informative empty state rather than an error.",
  "- **AgentStats isn't present on every subgraph** — `AgentStats` is a pre-computed summary entity (totals, averages, last activity) that the subgraph maintains as events come in. It's confirmed on Ethereum Sepolia but may be absent on other deployments. Four components rely on it exclusively — `ReputationScore`, `VerificationBadge`, `ValidationScore`, and `LastActivity`. These components treat a missing entity as an empty state rather than an error, so they'll fall back gracefully on chains without it.",
  "- **Four states per component** — Every component needs loading, error, empty, and not-found states handled — not just the happy path.",
  "",
  "Every component in this library handles all of this internally. You pass two identifiers and get a working UI backed by verified on-chain data. Queries are minimal per-component — `ReputationScore` fetches 2 fields, not 20+. Caching and request deduplication are automatic via TanStack Query, so multiple components targeting the same agent share a single network request.",
].join("\n")

const installationBody = [
  "Install the package, add peer dependencies, and configure your Graph API key — then drop any component into your app with a single import.",
  "",
  "## Install",
  "",
  "```bash",
  "npm install {{PACKAGE_NAME}}",
  "```",
  "",
  "or",
  "",
  "```bash",
  "pnpm add {{PACKAGE_NAME}}",
  "yarn add {{PACKAGE_NAME}}",
  "```",
  "",
  "## Peer Dependencies",
  "",
  "The library requires React and TanStack Query as peer dependencies:",
  "",
  "```bash",
  "npm install react react-dom @tanstack/react-query",
  "```",
  "",
  "Requires React 18 or 19, and `@tanstack/react-query` v5.",
  "",
  "If you already have React in your project, you only need to add `@tanstack/react-query`. TanStack Query handles caching and deduplication so multiple components on the same page don't make redundant network requests.",
  "",
  "## Get a Graph API Key",
  "",
  "Components fetch agent data from [The Graph](https://thegraph.com/studio/), a blockchain indexing service. Sign up at [thegraph.com/studio](https://thegraph.com/studio/) to get a free API key. There is a generous free tier — no credit card required for development.",
  "",
  "This is a **read-only query key** for usage tracking — it's safe to use in frontend code. It does not grant write access to anything.",
  "",
  "## Minimal Working Example",
  "",
  "```tsx",
  'import { ERC8004Provider, ReputationScore } from "{{PACKAGE_NAME}}"',
  "",
  "function App() {",
  "  return (",
  '    <ERC8004Provider apiKey="your-graph-api-key">',
  "      <ReputationScore",
  '        agentRegistry="eip155:8453:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"',
  "        agentId={2290}",
  "      />",
  "    </ERC8004Provider>",
  "  )",
  "}",
  "```",
  "",
  "The component handles all data fetching internally. `ERC8004Provider` auto-creates a TanStack Query client if you haven't set one up.",
  "",
  "> **In production:** load the API key from an environment variable rather than hardcoding it.",
  "",
  "```tsx",
  "// Vite",
  "apiKey={import.meta.env.VITE_GRAPH_API_KEY}",
  "",
  "// Next.js",
  "apiKey={process.env.NEXT_PUBLIC_GRAPH_API_KEY}",
  "```",
  "",
  "Graph API keys are safe in frontend code (see [API Keys](/docs/api-keys)) — env vars are about keeping keys out of your repo and swappable per environment.",
  "",
  "## If You Already Use TanStack Query",
  "",
  "Wrap with your own `QueryClientProvider`. `ERC8004Provider` detects an existing QueryClient and shares it — no duplicate clients, no wasted cache.",
  "",
  "```tsx",
  'import { QueryClient, QueryClientProvider } from "@tanstack/react-query"',
  'import { ERC8004Provider, ReputationScore } from "{{PACKAGE_NAME}}"',
  "",
  "const queryClient = new QueryClient()",
  "",
  "function App() {",
  "  return (",
  "    <QueryClientProvider client={queryClient}>",
  '      <ERC8004Provider apiKey="your-graph-api-key">',
  "        <ReputationScore",
  '          agentRegistry="eip155:8453:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"',
  "          agentId={2290}",
  "        />",
  "      </ERC8004Provider>",
  "    </QueryClientProvider>",
  "  )",
  "}",
  "```",
  "",
  "## Using AgentProvider for Profile Pages",
  "",
  "When rendering multiple components for the same agent, use `AgentProvider` to avoid repeating `agentRegistry` and `agentId` on every component. Individual components can still override with their own props.",
  "",
  "```tsx",
  'import { AgentProvider, AgentCard, ReputationScore, FeedbackList } from "{{PACKAGE_NAME}}"',
  "",
  '<AgentProvider agentRegistry="eip155:8453:0x..." agentId={2290}>',
  "  <AgentCard />",
  "  <ReputationScore />",
  "  <FeedbackList />",
  "</AgentProvider>",
  "```",
  "",
  "## Troubleshooting",
  "",
  "- **Nothing renders, no errors.** Check that components are wrapped in `<ERC8004Provider>`. Verify `agentRegistry` matches the format `eip155:{chainId}:{contractAddress}` exactly.",
  '- **"Failed to fetch" or 401/403 errors.** Your Graph API key is missing, invalid, or rate-limited. Double-check the key in your provider matches the one from the Graph Studio dashboard.',
  '- **Component shows "not found" state.** The `agentId` doesn\'t exist on the chain specified by `agentRegistry`. Verify the chain ID in the registry string matches where the agent is actually registered.',
  "- **Multiple components re-fetching the same data.** Ensure a single `QueryClient` instance is used (or let `ERC8004Provider` create one). A new `QueryClient` on every render defeats caching.",
  "",
  "## Next Steps",
  "",
  "- [Concepts](/docs/concepts) — understand what `agentRegistry` and `agentId` mean.",
  "- [Components](/docs/components) — browse all available components with live previews.",
  "- [Recipes](/docs/recipes) — see full page-level examples ready to copy.",
].join("\n")

const conceptsBody = [
  "What you need to know about ERC-8004 to use this library — no protocol deep-dive required.",
  "",
  "## What is ERC-8004?",
  "",
  "ERC-8004 is an Ethereum standard for on-chain AI agent identity. It lets agents register themselves on the blockchain with a name, description, image, and service endpoints — and lets users leave feedback and validations. Think of it like a public profile + review system for AI agents, but the data lives on-chain so it can't be faked.",
  "",
  "## Why use this library?",
  "",
  "For the specific Subgraph quirks this library handles on your behalf, see the [Introduction](/docs/introduction). Two gaps in the underlying data are worth flagging up front, since they shape the empty states you'll see:",
  "",
  "> **Warning — Validation Registry isn't on mainnet yet:** The smart contracts are only deployed on testnets (Sepolia confirmed). The subgraph schema supports validation entities across all deployments, so `VerificationBadge`, `ValidationScore`, and `ValidationList` will build and test end-to-end on Sepolia. On mainnet, validation queries return empty by design, not because something is broken. Components must render an informative empty state rather than an error.",
  "",
  "> **Note — AgentStats isn't present on every subgraph:** `AgentStats` is a pre-computed summary entity (totals, averages, last activity) that the subgraph maintains as events come in. It's confirmed on Ethereum Sepolia but may be absent on other deployments. Four components rely on it exclusively — `ReputationScore`, `VerificationBadge`, `ValidationScore`, and `LastActivity`. These components treat a missing entity as an empty state rather than an error, so they'll fall back gracefully on chains without it.",
  "",
  "## The Three Registries",
  "",
  "### Identity Registry",
  "",
  'Like a business registration. Each agent gets an NFT (ERC-721 token) with a registration file containing its name, description, image, and service endpoints. This is where "who is this agent?" data lives.',
  "",
  "_Components: AgentName, AgentImage, AgentDescription, AgentCard, EndpointStatus._",
  "",
  "### Reputation Registry",
  "",
  'Like a review system. Users who interact with an agent can leave feedback — a score, tags describing what the agent does well, and optional written reviews. This is where "is this agent any good?" data lives.',
  "",
  "_Components: ReputationScore, ReputationTimeline, ReputationDistribution, FeedbackList, TagCloud._",
  "",
  "### Validation Registry",
  "",
  'Like a certification body. Independent third-party verifiers can assess an agent and record a score (0–100). This is where "has this agent been independently verified?" data lives.',
  "",
  "_Components: VerificationBadge, ValidationScore, ValidationList._",
  "",
  "> **Warning:** Not yet deployed to any mainnet chain. Testnet (Sepolia) only. Components return empty on mainnet.",
  "",
  "## Agent Identity: agentRegistry + agentId",
  "",
  "Every component takes two props that together uniquely identify an agent across any chain:",
  "",
  "- **`agentRegistry`** — A string in the format `eip155:{chainId}:{contractAddress}`. Breaking it down:",
  "  - `eip155` — namespace meaning it's an Ethereum-compatible chain.",
  "  - `chainId` — identifies which blockchain (1 = Ethereum, 8453 = Base, etc.).",
  "  - `contractAddress` — where the Identity Registry smart contract is deployed.",
  "- **`agentId`** — The ERC-721 token ID, the unique number assigned to this agent when it registered.",
  "",
  'Example: `agentRegistry="eip155:8453:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"` + `agentId={2290}` means "agent #2290 on the Base blockchain."',
  "",
  "## Two Ways to Pass Identifiers",
  "",
  "Components accept identifiers two ways.",
  "",
  "**Directly as props** — fine for a single component:",
  "",
  "```tsx",
  '<ReputationScore agentRegistry="eip155:8453:0x..." agentId={2290} />',
  "```",
  "",
  "**Via `AgentProvider`** — cleaner when rendering multiple components for the same agent:",
  "",
  "```tsx",
  '<AgentProvider agentRegistry="eip155:8453:0x..." agentId={2290}>',
  "  <AgentCard />",
  "  <ReputationScore />",
  "  <FeedbackList />",
  "</AgentProvider>",
  "```",
  "",
  "Props on individual components override the provider, so you can mix both patterns when needed.",
  "",
  "## Trustless Data",
  "",
  "Components never accept display data as props. You only pass identifiers — the component fetches verified data from the blockchain internally. This means the data you see is guaranteed to be real on-chain data, not something that could be spoofed by a developer passing fake props.",
  "",
  'This differs from a typical React component where you\'d pass something like `<AgentCard name="Alice" score={4.8} />` — those values could be anything the developer types. Here, the component fetches `name` and `score` itself from on-chain data, so what\'s displayed is what\'s actually registered.',
  "",
  "## Supported Chains",
  "",
  "| Chain | ID |",
  "| --- | --- |",
  "| Ethereum Mainnet | 1 |",
  "| Base Mainnet | 8453 |",
  "| Polygon Mainnet | 137 |",
  "| BSC Mainnet | 56 |",
  "| Monad Mainnet | 143 |",
  "| Ethereum Sepolia (testnet) | 11155111 |",
  "| Base Sepolia (testnet) | 84532 |",
  "| BSC Chapel (testnet) | 97 |",
  "| Monad Testnet (testnet) | 10143 |",
  "",
  "Note: `AgentStats` — the entity that powers `ReputationScore`, `VerificationBadge`, `ValidationScore`, and `LastActivity` — is not present on every chain's subgraph. It's confirmed on Ethereum Sepolia. Affected components will render their empty state on chains without it.",
  "",
  "## Where the Data Comes From",
  "",
  "All data is fetched from [The Graph](https://thegraph.com) — a decentralised indexing service that watches the blockchain, extracts ERC-8004 events, and serves them via fast GraphQL queries. You don't need to understand GraphQL to use this library — components handle all queries internally. You just need a free API key from The Graph.",
].join("\n")

const apiKeysBody = [
  "Components fetch agent data from The Graph, a blockchain indexing service. You need a free API key to authenticate your requests.",
  "",
  "## How to Get One",
  "",
  "1. Go to [thegraph.com/studio](https://thegraph.com/studio/) and create an account.",
  "2. Create an API key in the dashboard.",
  "3. Copy the key.",
  "4. Pass it to `ERC8004Provider`.",
  "",
  "```tsx",
  '<ERC8004Provider apiKey="your-graph-api-key">',
  "  {/* your components */}",
  "</ERC8004Provider>",
  "```",
  "",
  "## Is It Safe to Use in Frontend Code?",
  "",
  "Yes. Graph API keys are read-only query keys — they only authorise GraphQL reads against Subgraphs. They cannot modify any on-chain data, they cannot write to any database, and they cannot access anything outside your Subgraph queries. Their only purpose is usage tracking and rate limiting.",
  "",
  "This is the same pattern used by every dApp that queries The Graph, including most major DeFi protocols. Exposing the key in frontend code is expected and safe.",
  "",
  "## Free Tier",
  "",
  "The Graph offers a free tier that's sufficient for development and moderate production use. Sign in to [the Graph Studio dashboard](https://thegraph.com/studio/) to view current limits and usage for your key.",
  "",
  "## Custom Subgraph Endpoint",
  "",
  "If you run your own Subgraph or use a different indexer, use the `subgraphOverrides` prop on `ERC8004Provider` to override the default endpoint for any chain:",
  "",
  "```tsx",
  "<ERC8004Provider",
  '  apiKey="your-key"',
  "  subgraphOverrides={{",
  '    1: "https://your-custom-subgraph.com/ethereum",',
  '    8453: "https://your-custom-subgraph.com/base",',
  "  }}",
  ">",
  "```",
  "",
  "Keys are chain IDs. Overrides apply per-chain — chains not listed fall back to the default Graph endpoints.",
].join("\n")

// Components guide is intentionally minimal — `generate-llms.ts` appends the
// grouped component list dynamically from its existing GROUPS constant so the
// guide stays in sync with the index.
const componentsBody = [
  "All components in the library, grouped by registry. Each component fetches its own data — pass two identifiers and it works.",
  "",
  "Every data component handles loading, error, empty, and not-found states internally. You pass `agentRegistry` and `agentId` (or rely on an enclosing `AgentProvider`) and the component does the rest.",
].join("\n")

const themingBody = [
  "`{{PACKAGE_NAME}}` uses CSS variables for theming. This gives you a set of named color and radius tokens that every component references. Override those tokens in your CSS to change the look of the entire library without touching component code.",
  "",
  "Out of the box, the library ships with a light theme and a dark theme. No configuration required — just import the stylesheet and go. Colors use OKLCH rather than hex. OKLCH is perceptually uniform — lightening or darkening a value produces a predictable visual shift, which makes themes easier to build and tweak.",
  "",
  "```tsx",
  'import "{{PACKAGE_NAME}}/styles.css"',
  "```",
  "",
  "## OKLCH Color Format",
  "",
  "All color tokens are raw [OKLCH](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch) values — three space-separated numbers for `lightness chroma hue`:",
  "",
  "- **Lightness** — `0` (black) to `1` (white).",
  "- **Chroma** — saturation. `0` is gray, higher values are more vivid.",
  "- **Hue** — color angle in degrees. `260` blue, `145` green, `300` purple, `25` red-orange.",
  "",
  "For neutral grays, chroma and hue are both `0` (e.g., `0.556 0 0` is a medium gray). Use [oklch.com](https://oklch.com) to pick values interactively.",
  "",
  "## Playground",
  "",
  "An interactive playground for previewing presets and seeing live token changes is available on the live site at {{SITE_URL}}/docs/theming. The CSS shown there is exactly what you would write to reproduce a theme in your own app.",
  "",
  "## How It Works",
  "",
  "Every component in the library uses Tailwind classes like `bg-erc8004-card` and `text-erc8004-muted-fg` instead of hardcoded colors. These classes reference CSS variables defined under the `.erc8004` scope — a wrapper that the `ERC8004Provider` renders automatically.",
  "",
  "Because the variables are scoped to `.erc8004`, they never conflict with your app's own styles. If your app uses shadcn, Tailwind's default palette, or any other styling system, everything coexists cleanly. Dark and light mode work by swapping the variable values when a `.dark` or `.light` class is present on an ancestor — see [Dark and Light Mode](#dark-and-light-mode) below.",
  "",
  "## Three Ways to Customize",
  "",
  "Pick the broadest method that does the job. Use CSS variables to retheme everything, provider `className` to scope a theme to a section of your app, or component `className` for one-off tweaks.",
  "",
  "### 1. CSS Variable Overrides — retheme everything",
  "",
  "Override the variables in your own stylesheet. Every component picks up the changes instantly.",
  "",
  "```css",
  "/* your-app.css */",
  ".erc8004 {",
  "  --erc8004-accent: 0.55 0.25 300;   /* purple instead of blue */",
  "  --erc8004-radius: 0.75rem;          /* rounder corners */",
  "}",
  "```",
  "",
  "### 2. Provider `className` — scope a theme to a subtree",
  "",
  "The provider accepts a `className` prop that gets merged onto the `.erc8004` wrapper. Two common uses:",
  "",
  "**Toggle light or dark mode:**",
  "",
  "```tsx",
  '<ERC8004Provider apiKey="..." className="dark">',
  "  {/* dark theme active for all components inside */}",
  "</ERC8004Provider>",
  "",
  '<ERC8004Provider apiKey="..." className="light">',
  "  {/* forces light theme, even inside a .dark ancestor */}",
  "</ERC8004Provider>",
  "```",
  "",
  "**Apply a custom theme class:**",
  "",
  "```css",
  "/* Define a custom theme class */",
  ".erc8004.my-brand {",
  "  --erc8004-accent: 0.55 0.25 300;",
  "  --erc8004-radius: 0.75rem;",
  "}",
  "```",
  "",
  "```tsx",
  '<ERC8004Provider apiKey="..." className="my-brand">',
  "  {/* all components inside use the custom theme */}",
  "</ERC8004Provider>",
  "```",
  "",
  "### 3. Component `className` — one-off tweaks",
  "",
  "Every component accepts a `className` prop. Your classes override the component's defaults when they target the same CSS property — padding replaces padding, background replaces background.",
  "",
  "```tsx",
  "<ReputationScore",
  '  agentRegistry="eip155:8453:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"',
  "  agentId={2290}",
  '  className="shadow-lg rounded-2xl p-6"',
  "/>",
  "```",
  "",
  "## Token Convention",
  "",
  "Tokens follow a **background / foreground pair** pattern. The base token controls the surface color, and the `-fg` suffixed token controls the text and icon color that sits on that surface.",
  "",
  "For example, given these variables:",
  "",
  "```css",
  ".erc8004 {",
  "  --erc8004-card: 1 0 0;          /* white surface */",
  "  --erc8004-card-fg: 0.145 0 0;   /* near-black text */",
  "}",
  "```",
  "",
  "A component using `bg-erc8004-card text-erc8004-card-fg` will render dark text on a white card. Override the variables, and the component adapts — you never need to change the component itself.",
  "",
  "## Dark and Light Mode",
  "",
  "The default theme is light — no setup needed. Adding a `.dark` ancestor class switches components to dark mode. This is the standard Tailwind dark mode convention that most apps already use.",
  "",
  "```html",
  '<body class="dark">',
  "  <!-- ERC8004 components automatically use dark colors -->",
  "</body>",
  "```",
  "",
  "Adding a `.light` ancestor class explicitly forces light mode, even inside a `.dark` parent. This is useful for embedding components in a light section of an otherwise-dark app.",
  "",
  "```html",
  '<body class="dark">',
  "  <!-- dark everywhere... -->",
  "",
  '  <div class="light">',
  "    <!-- ...except these components stay light -->",
  '    <ERC8004Provider apiKey="...">',
  '      <ReputationScore agentRegistry="..." agentId={2290} />',
  "    </ERC8004Provider>",
  "  </div>",
  "</body>",
  "```",
  "",
  "Either class can go on `<body>`, a container `div`, or directly on `ERC8004Provider` via the `className` prop. If your app already handles dark mode by toggling a `.dark` class, the library follows along automatically.",
  "",
  "**Overriding dark mode colors**",
  "",
  "To customize specific colors in dark mode, target `.dark .erc8004`:",
  "",
  "```css",
  ".dark .erc8004 {",
  "  --erc8004-accent: 0.7 0.2 260;      /* brighter blue in dark mode */",
  "  --erc8004-card: 0.18 0.01 260;      /* slight blue tint to cards */",
  "}",
  "```",
  "",
  "**Overriding light mode colors**",
  "",
  "Similarly, to customize colors only in explicit light mode, target `.light .erc8004`:",
  "",
  "```css",
  ".light .erc8004 {",
  "  --erc8004-accent: 0.5 0.22 260;     /* deeper blue in light mode */",
  "  --erc8004-card: 0.98 0.005 80;      /* warm white cards */",
  "}",
  "```",
  "",
  "## Token Reference",
  "",
  "**Surfaces**",
  "",
  "| Token | CSS Variable | Default (Light) | What it controls |",
  "| --- | --- | --- | --- |",
  "| Background | `--erc8004-bg` | `1 0 0` | Default component background |",
  "| Foreground | `--erc8004-fg` | `0.145 0 0` | Default text color |",
  "| Card | `--erc8004-card` | `1 0 0` | Elevated surface background (cards, panels) |",
  "| Card foreground | `--erc8004-card-fg` | `0.145 0 0` | Text on elevated surfaces |",
  "| Muted | `--erc8004-muted` | `0.97 0 0` | Subtle backgrounds (tags, skeletons, empty states) |",
  "| Muted foreground | `--erc8004-muted-fg` | `0.556 0 0` | Secondary text (timestamps, descriptions, helper text) |",
  "",
  "**Accent**",
  "",
  "| Token | CSS Variable | Default (Light) | What it controls |",
  "| --- | --- | --- | --- |",
  "| Accent | `--erc8004-accent` | `0.55 0.2 260` | Brand color, primary actions, active highlights |",
  "| Accent foreground | `--erc8004-accent-fg` | `0.985 0 0` | Text on accent surfaces |",
  "",
  "**Semantic**",
  "",
  "| Token | CSS Variable | Default (Light) | What it controls |",
  "| --- | --- | --- | --- |",
  "| Positive | `--erc8004-positive` | `0.55 0.17 145` | Positive scores, success indicators |",
  "| Positive foreground | `--erc8004-positive-fg` | `0.985 0 0` | Text on positive surfaces |",
  "| Negative | `--erc8004-negative` | `0.55 0.2 25` | Negative scores, error states |",
  "| Negative foreground | `--erc8004-negative-fg` | `0.985 0 0` | Text on negative surfaces |",
  "",
  "**Borders & Focus**",
  "",
  "| Token | CSS Variable | Default (Light) | What it controls |",
  "| --- | --- | --- | --- |",
  "| Border | `--erc8004-border` | `0.922 0 0` | All borders and dividers |",
  "| Ring | `--erc8004-ring` | `0.55 0.2 260` | Focus ring on interactive elements |",
  "",
  "**Chart Palette**",
  "",
  "| Token | CSS Variable | Default (Light) | What it controls |",
  "| --- | --- | --- | --- |",
  "| Chart 1 | `--erc8004-chart-1` | `0.55 0.2 260` | First chart color (blue) |",
  "| Chart 2 | `--erc8004-chart-2` | `0.6 0.18 145` | Second chart color (green) |",
  "| Chart 3 | `--erc8004-chart-3` | `0.6 0.2 25` | Third chart color (red-orange) |",
  "| Chart 4 | `--erc8004-chart-4` | `0.65 0.2 310` | Fourth chart color (purple) |",
  "| Chart 5 | `--erc8004-chart-5` | `0.7 0.15 70` | Fifth chart color (gold) |",
  "",
  "**Radius**",
  "",
  "| Token | CSS Variable | Default | What it controls |",
  "| --- | --- | --- | --- |",
  "| Radius | `--erc8004-radius` | `0.5rem` | Base corner radius — all sizes derive from this |",
  "",
  "## Radius Scale",
  "",
  "The library derives a set of radius sizes from the single `--erc8004-radius` base value:",
  "",
  "| Class | Size | Formula |",
  "| --- | --- | --- |",
  "| `rounded-erc8004-sm` | 0.3rem | radius × 0.6 |",
  "| `rounded-erc8004-md` | 0.4rem | radius × 0.8 |",
  "| `rounded-erc8004-lg` | 0.5rem | radius × 1.0 (the base) |",
  "| `rounded-erc8004-xl` | 0.7rem | radius × 1.4 |",
  "| `rounded-erc8004-2xl` | 0.9rem | radius × 1.8 |",
  "",
  "Change `--erc8004-radius` once, and the entire radius scale updates proportionally:",
  "",
  "```css",
  ".erc8004 {",
  "  --erc8004-radius: 0.75rem;  /* everything gets rounder */",
  "}",
  "```",
  "",
  "```css",
  ".erc8004 {",
  "  --erc8004-radius: 0;  /* sharp corners everywhere */",
  "}",
  "```",
  "",
  "## Examples",
  "",
  "**Match your brand color**",
  "",
  "```css",
  ".erc8004 {",
  "  --erc8004-accent: 0.55 0.25 300;      /* purple */",
  "  --erc8004-ring: 0.55 0.25 300;        /* focus rings match */",
  "}",
  "```",
  "",
  "**Warm neutral palette**",
  "",
  "```css",
  ".erc8004 {",
  "  --erc8004-bg: 0.98 0.005 80;          /* warm white */",
  "  --erc8004-card: 0.96 0.008 80;        /* warm off-white */",
  "  --erc8004-muted: 0.94 0.01 80;        /* warm gray */",
  "  --erc8004-border: 0.9 0.01 80;        /* warm border */",
  "}",
  "```",
  "",
  "**Compact with sharp corners**",
  "",
  "```tsx",
  "<ReputationScore",
  '  agentRegistry="eip155:8453:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"',
  "  agentId={2290}",
  '  className="p-2 text-sm rounded-none"',
  "/>",
  "```",
  "",
  "**Full custom theme via CSS class**",
  "",
  "```css",
  "/* teal-brand.css */",
  ".erc8004.teal-brand {",
  "  --erc8004-accent: 0.6 0.22 160;       /* teal */",
  "  --erc8004-positive: 0.6 0.22 160;     /* match accent for positive */",
  "  --erc8004-negative: 0.55 0.2 0;       /* warm red */",
  "  --erc8004-border: 0.88 0.01 160;      /* subtle teal borders */",
  "  --erc8004-radius: 1rem;               /* very rounded */",
  "}",
  "```",
  "",
  "```tsx",
  '<ERC8004Provider apiKey="your-graph-api-key" className="teal-brand">',
  "  {/* all components use the teal theme */}",
  "</ERC8004Provider>",
  "```",
  "",
  "## Provider Props",
  "",
  "The only theming-relevant prop on `ERC8004Provider` is `className`, which gets merged onto the `.erc8004` wrapper. See the [ERC8004Provider component page](/docs/components/erc8004-provider) for the full prop reference.",
  "",
  "```tsx",
  '<ERC8004Provider apiKey="..." className="dark my-theme">',
  "  {children}",
  "</ERC8004Provider>",
  "```",
  "",
  "## FAQ",
  "",
  "**Does the library ship its own font?**",
  "",
  "No. Components inherit `font-family` from their parent, so they adopt whatever typography your app uses. Set the font on `.erc8004` or any ancestor and components will follow. Some elements like numeric scores and addresses use monospace (`font-mono`) for readability, but no base font is bundled or required.",
  "",
  "**Can I force light mode inside a dark app?**",
  "",
  'Yes. Add `className="light"` to the provider (or any ancestor of the components you want to stay light). This works even when a higher ancestor has `.dark` set.',
  "",
  "**Will this conflict with my app's Tailwind config?**",
  "",
  "No. All tokens are namespaced under `erc8004-` and scoped to the `.erc8004` class. They don't touch your app's `--primary`, `--background`, or any other standard Tailwind/shadcn variables.",
  "",
  "**Do I need Tailwind in my project to use `className`?**",
  "",
  "Not strictly — `className` accepts any CSS class string. But the library is built with Tailwind, so overriding with Tailwind classes gives you the most predictable results since `tailwind-merge` understands the conflict resolution. If your project doesn't use Tailwind, you can still pass regular CSS classes or use the CSS variable overrides instead.",
  "",
  "**Can I theme individual components differently?**",
  "",
  "Yes. Wrap a subset of components in a `div` with overridden variables:",
  "",
  "```tsx",
  '<ERC8004Provider apiKey="...">',
  "  {/* These use the default theme */}",
  '  <ReputationScore agentRegistry="..." agentId={1} />',
  "",
  "  {/* These use a custom accent */}",
  '  <div style={{ "--erc8004-accent": "0.55 0.25 300" } as React.CSSProperties}>',
  '    <ReputationScore agentRegistry="..." agentId={2} />',
  '    <FeedbackList agentRegistry="..." agentId={2} />',
  "  </div>",
  "</ERC8004Provider>",
  "```",
  "",
  "Since CSS variables inherit downward, any `div` that redefines a variable creates a new scope for its children.",
  "",
  "**What color format should I use?**",
  "",
  "Raw OKLCH values: three space-separated numbers for lightness, chroma, and hue. For example, `0.55 0.2 260` is a medium-brightness blue. You can use any OKLCH color picker to find values. For grays, set chroma and hue to `0` (e.g., `0.5 0 0` is medium gray).",
].join("\n")

const recipesBody = [
  "Complete page-level compositions ready to copy. Each example is self-contained and uses the same demo agent used throughout the docs.",
  "",
  "## Agent Profile Page",
  "",
  "A full profile layout covering identity, reputation, and validation. `AgentProvider` eliminates prop repetition — every child component inherits the same agent identity.",
  "",
  "```tsx",
  "import {",
  "  ERC8004Provider,",
  "  AgentProvider,",
  "  AgentCard,",
  "  EndpointStatus,",
  "  ReputationScore,",
  "  ReputationTimeline,",
  "  ReputationDistribution,",
  "  FeedbackList,",
  "  TagCloud,",
  "  VerificationBadge,",
  "  ValidationScore,",
  "  LastActivity,",
  '} from "{{PACKAGE_NAME}}"',
  "",
  "function AgentProfile({ registry, agentId }: { registry: string; agentId: number }) {",
  "  return (",
  "    <AgentProvider agentRegistry={registry} agentId={agentId}>",
  "      {/* Identity section */}",
  "      <AgentCard />",
  "      <EndpointStatus />",
  "",
  "      {/* Reputation section */}",
  '      <div style={{ display: "flex", gap: "1rem", alignItems: "center" }}>',
  "        <ReputationScore />",
  "        <VerificationBadge />",
  "        <LastActivity />",
  "      </div>",
  "      <TagCloud />",
  "      <ReputationTimeline />",
  "      <ReputationDistribution />",
  "      <FeedbackList />",
  "",
  "      {/* Validation section */}",
  "      <ValidationScore />",
  "    </AgentProvider>",
  "  )",
  "}",
  "```",
  "",
  "## Marketplace Listing Row",
  "",
  "Compact row for search results or directory listings. Renders fast — each component fetches only the fields it needs.",
  "",
  "```tsx",
  "import {",
  "  AgentProvider,",
  "  AgentImage,",
  "  AgentName,",
  "  ReputationScore,",
  "  VerificationBadge,",
  "  LastActivity,",
  '} from "{{PACKAGE_NAME}}"',
  "",
  "function AgentRow({ registry, agentId }: { registry: string; agentId: number }) {",
  "  return (",
  "    <AgentProvider agentRegistry={registry} agentId={agentId}>",
  '      <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>',
  "        <AgentImage />",
  "        <AgentName />",
  "        <ReputationScore />",
  "        <VerificationBadge />",
  "        <LastActivity />",
  "      </div>",
  "    </AgentProvider>",
  "  )",
  "}",
  "```",
  "",
  "## Agent Comparison",
  "",
  "Side-by-side comparison of multiple agents. Each `AgentProvider` scopes its context independently — components inside one provider won't bleed into another.",
  "",
  "```tsx",
  'import { AgentProvider, AgentCard, ReputationScore, TagCloud } from "{{PACKAGE_NAME}}"',
  "",
  "function CompareAgents({ agents }: { agents: { registry: string; id: number }[] }) {",
  "  return (",
  "    <div",
  "      style={{",
  '        display: "grid",',
  "        gridTemplateColumns: `repeat(${agents.length}, 1fr)`,",
  '        gap: "1rem",',
  "      }}",
  "    >",
  "      {agents.map((agent) => (",
  "        <AgentProvider",
  "          key={`${agent.registry}-${agent.id}`}",
  "          agentRegistry={agent.registry}",
  "          agentId={agent.id}",
  "        >",
  "          <AgentCard />",
  "          <ReputationScore />",
  "          <TagCloud />",
  "        </AgentProvider>",
  "      ))}",
  "    </div>",
  "  )",
  "}",
  "```",
  "",
  "## Minimal Embed",
  "",
  "A small inline trust signal for chat interfaces, sidebars, or tooltips.",
  "",
  "```tsx",
  'import { AgentProvider, AgentName, ReputationScore, VerificationBadge } from "{{PACKAGE_NAME}}"',
  "",
  "function AgentTrustBadge({ registry, agentId }: { registry: string; agentId: number }) {",
  "  return (",
  "    <AgentProvider agentRegistry={registry} agentId={agentId}>",
  '      <div style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem" }}>',
  "        <AgentName />",
  "        <ReputationScore />",
  "        <VerificationBadge />",
  "      </div>",
  "    </AgentProvider>",
  "  )",
  "}",
  "```",
  "",
  "> **Cache efficiency:** When multiple components target the same agent on the same page, TanStack Query deduplicates the Subgraph requests automatically. Only one network call happens, and all components read from the shared cache. You don't need to manage this.",
].join("\n")

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const GUIDE_REGISTRY: Record<string, GuideDoc> = {
  introduction: {
    slug: "introduction",
    name: "Introduction",
    description: "Why this library exists and what problems it solves.",
    body: introductionBody,
  },
  installation: {
    slug: "installation",
    name: "Installation",
    description:
      "Install the package, set up the provider, write your first component.",
    body: installationBody,
  },
  concepts: {
    slug: "concepts",
    name: "Concepts",
    description:
      "Core concepts: registries, agentRegistry/agentId, trustless data, supported chains.",
    body: conceptsBody,
  },
  "api-keys": {
    slug: "api-keys",
    name: "API Keys",
    description:
      "How to get a Graph API key and why it's safe to use in frontend code.",
    body: apiKeysBody,
  },
  components: {
    slug: "components",
    name: "Components",
    description: "All components in the library, grouped by registry.",
    body: componentsBody,
  },
  theming: {
    slug: "theming",
    name: "Theming",
    description: "Styling, dark mode, and customisation patterns.",
    body: themingBody,
  },
  recipes: {
    slug: "recipes",
    name: "Recipes",
    description:
      "Complete page-level compositions: profile pages, marketplace rows, comparisons.",
    body: recipesBody,
  },
}

/**
 * Display order for guides in `llms.txt` and `llms-full.txt`. Independent of
 * Object key iteration order so reordering stays deterministic.
 */
export const GUIDE_ORDER: string[] = [
  "introduction",
  "installation",
  "concepts",
  "api-keys",
  "components",
  "theming",
  "recipes",
]
