/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsRecipesRouteImport } from './routes/docs/recipes'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsConceptsRouteImport } from './routes/docs/concepts'
import { Route as DocsApiKeysRouteImport } from './routes/docs/api-keys'
import { Route as DocsComponentsIndexRouteImport } from './routes/docs/components/index'
import { Route as DocsComponentsSlugRouteImport } from './routes/docs/components/$slug'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRecipesRoute = DocsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiKeysRoute = DocsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsSlugRoute = DocsComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/recipes': typeof DocsRecipesRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/components/$slug': typeof DocsComponentsSlugRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/recipes': typeof DocsRecipesRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/components/$slug': typeof DocsComponentsSlugRoute
  '/docs/components': typeof DocsComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/recipes': typeof DocsRecipesRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/components/$slug': typeof DocsComponentsSlugRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/api-keys'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/recipes'
    | '/docs/theming'
    | '/docs/components/$slug'
    | '/docs/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/api-keys'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/recipes'
    | '/docs/theming'
    | '/docs/components/$slug'
    | '/docs/components'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/api-keys'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/recipes'
    | '/docs/theming'
    | '/docs/components/$slug'
    | '/docs/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/recipes': {
      id: '/docs/recipes'
      path: '/recipes'
      fullPath: '/docs/recipes'
      preLoaderRoute: typeof DocsRecipesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-keys': {
      id: '/docs/api-keys'
      path: '/api-keys'
      fullPath: '/docs/api-keys'
      preLoaderRoute: typeof DocsApiKeysRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/': {
      id: '/docs/components/'
      path: '/components'
      fullPath: '/docs/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/$slug': {
      id: '/docs/components/$slug'
      path: '/components/$slug'
      fullPath: '/docs/components/$slug'
      preLoaderRoute: typeof DocsComponentsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsApiKeysRoute: typeof DocsApiKeysRoute
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsRecipesRoute: typeof DocsRecipesRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsComponentsSlugRoute: typeof DocsComponentsSlugRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiKeysRoute: DocsApiKeysRoute,
  DocsConceptsRoute: DocsConceptsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsRecipesRoute: DocsRecipesRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsComponentsSlugRoute: DocsComponentsSlugRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
